BEGIN

INSERT INTO DELIVERY_COMPANIES (BUSINESS_NAME, TAX_NUMBER, FREQUENCY_RATE) VALUES('Rappo', 900622385, 'Mensual');
INSERT INTO DELIVERY_COMPANIES (BUSINESS_NAME, TAX_NUMBER, FREQUENCY_RATE) VALUES('Dodo Foods', 900842374, 'Mensual');
INSERT INTO DELIVERY_COMPANIES (BUSINESS_NAME, TAX_NUMBER, FREQUENCY_RATE) VALUES('Juber Eats', 900342981, 'Mensual');
INSERT INTO DELIVERY_COMPANIES (BUSINESS_NAME, TAX_NUMBER, FREQUENCY_RATE) VALUES('Domicilios.net', 900578412, 'Mensual');
INSERT INTO DELIVERY_COMPANIES (BUSINESS_NAME, TAX_NUMBER, FREQUENCY_RATE) VALUES('MenuPrime', 860439782, 'Mensual');

COMMIT;

EXCEPTION
   WHEN OTHERS THEN
      ROLLBACK;
      raise_application_error(-20000,SQLCODE||'=>'|| SQLERRM ,true); 
	
END;
