
BEGIN

UPDATE DELIVERIES_MENUS dm 
SET dm.UNIT_COST = 
	( SELECT m.UNIT_COST 
		FROM MENUS m 
		WHERE dm.FK_MENU_ID = m.MENU_ID );

UPDATE DELIVERIES_MENUS dm 
SET dm.TOTAL_COST  = (dm.UNIT_COST * dm.QUANTITY);

UPDATE DELIVERIES d 
SET d.TOTAL_AMOUNT = 
	(SELECT SUM(dm.TOTAL_COST) 
		FROM DELIVERIES_MENUS dm
		WHERE d.DELIVERY_ID = dm.FK_DELIVERY_ID
		GROUP BY dm.FK_DELIVERY_ID);
		
COMMIT;

EXCEPTION
   WHEN OTHERS THEN
      ROLLBACK;
      raise_application_error(-20000,SQLCODE||'=>'|| SQLERRM ,true);   
END;