BEGIN
INSERT INTO MENUS (DESCRIPTION, UNIT_COST) VALUES ('Bandeja de res', 20000);
INSERT INTO MENUS (DESCRIPTION, UNIT_COST) VALUES ('Bandeja de cerdo', 19000);
INSERT INTO MENUS (DESCRIPTION, UNIT_COST) VALUES ('Bandeja de chicharron', 22000);
INSERT INTO MENUS (DESCRIPTION, UNIT_COST) VALUES ('Bandeja paisa', 25000);
INSERT INTO MENUS (DESCRIPTION, UNIT_COST) VALUES ('Ajiaco', 23000);
INSERT INTO MENUS (DESCRIPTION, UNIT_COST) VALUES ('Lechona', 21000);
INSERT INTO MENUS (DESCRIPTION, UNIT_COST) VALUES ('Sancocho', 24000);
INSERT INTO MENUS (DESCRIPTION, UNIT_COST) VALUES ('Bandeja de higado encebollado', 18000);

COMMIT;
EXCEPTION
   WHEN OTHERS THEN
      ROLLBACK;
      raise_application_error(-20000,SQLCODE||'=>'|| SQLERRM ,true);   
END;