BEGIN
INSERT INTO AVAILABLE_FIELDS (TABLE_NAME, COLUMN_NAME) VALUES ('MENUPRIME_LOCATIONS', 'CITY');
INSERT INTO AVAILABLE_FIELDS (TABLE_NAME, COLUMN_NAME) VALUES ('DELIVERIES', 'PAYMENT_METHOD');
INSERT INTO AVAILABLE_FIELDS (TABLE_NAME, COLUMN_NAME) VALUES ('CUSTOMERS', 'FULL_NAME');
INSERT INTO AVAILABLE_FIELDS (TABLE_NAME, COLUMN_NAME) VALUES ('CUSTOMERS', 'CELLPHONE_NUMBER');
INSERT INTO AVAILABLE_FIELDS (TABLE_NAME, COLUMN_NAME) VALUES ('CUSTOMERS', 'DOCUMENT_TYPE');

COMMIT;
EXCEPTION
   WHEN OTHERS THEN
      ROLLBACK;
      raise_application_error(-20000,SQLCODE||'=>'|| SQLERRM ,true);   
END;